"""create sensor readings table

Revision ID: 8bce1260c5b1
Revises: 538d2e75ff03
Create Date: 2026-10-07 13:44:53.339278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bce1260c5b1'
down_revision: Union[str, Sequence[str], None] = '538d2e75ff03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('door', sa.Integer(), nullable=True),
    sa.Column('light', sa.Integer(), nullable=True),
    sa.Column('rain', sa.Integer(), nullable=True),
    sa.Column('gas', sa.Integer(), nullable=True),
    sa.Column('person', sa.Integer(), nullable=True),
    sa.Column('vibration', sa.Integer(), nullable=True),
    sa.Column('rfid', sa.String(length=255), nullable=True),
    sa.Column('roof', sa.Integer(), nullable=True),
    sa.Column('fan', sa.Integer(), nullable=True),
    sa.Column('led', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_device_id'), 'sensor_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_device_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
